# -*- coding: utf-8 -*-
"""TsunamiPool.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Fo1BqpCwXCbEAgMhTTd2wrqYVr-Dj3k

The equation with added terrain can be found here:
https://www.sciencedirect.com/science/article/pii/S1877750322002150
"""

import matplotlib.pyplot as plt
import numpy as np
import itertools, copy, sys
import pandas
np.set_printoptions(threshold=sys.maxsize)

def calculate_wave(i, j, u_t_1, u_t_2, t, C, g=9.81):
    h = 10/u_t_1.shape[0]
    X_1 = ((u_t_1[i+1, j] - u_t_1[i-1, j]) / 2*h)**2
    X_2 = u_t_1[i, j] * (
        (u_t_1[i+1, j]-2*u_t_1[i, j]+ u_t_1[i-1, j]) / h**2
    )
    X_3 = ((u_t_1[i, j+1] - u_t_1[i, j-1]) / 2*h)**2
    X_4 = u_t_1[i, j] * (
        (u_t_1[i, j+1]-2*u_t_1[i, j]+ u_t_1[i, j-1]) / h**2
    )

    X = X_1 + X_2 + X_3 + X_4

    val = u_t_1[i, j] + C * (u_t_1[i, j] - u_t_2[i, j]) + g * (t**2) * X
    return val

def wave_step(center, u_t_1, u_t_2, t, C, g=9.81):
   x, y = center
   size = u_t_1.shape[0]
   u_new = np.full(shape = (size,size), fill_value = 2, dtype = float)

   for i in range(1, size-1):
      for j in range(1, size-1):
         u_new[i, j] = calculate_wave(i, j, u_t_1, u_t_2, t, C, g)

        #  r = np.sqrt((i-x)**2 + (j-y)**2)
        #  u_new[i, j] += (t*t*(2 + 2 * np.exp(-(r**2))))
        #  u_new[i, j] += (t*t*2)

   return u_new, u_t_1

def create_board(size, center, water_lvl):
    x, y = center
    delta = 10 / size
    x *= delta
    y *= delta
    board = np.zeros((size, size))
    for i in range(size):
        for j in range(size):
            r = np.sqrt((i*delta-x)**2 + (j*delta-y)**2)
            board[i, j] = 2 + 2 * np.exp(-(r**2))

    return board

def wave_simulation(size, center, iterations, t, C, water_lvl=2):
    u_t_1 = create_board(size, center, water_lvl)
    u_t_2 = create_board(size, center, water_lvl)

    import time
    import pylab as pl
    from IPython import display

    # plt.figure()
    # plt.colorbar()
    for _ in range(iterations-1):
        u_t_1, u_t_2 = wave_step(center, u_t_1, u_t_2, t, C)

        if _ % 100 == 0:
          plt.figure()
          plt.imshow(u_t_1)

          plt.colorbar()
          display.clear_output(wait=True)
          display.display(pl.gcf())

    return u_t_1

b = wave_simulation(128, (64, 64), 1000, 0.001, 0.999)
# plt.imshow(b)
# plt.colorbar()
# print(b[64, 64])
print(b[0,60])
# print(pandas.DataFrame(b))

print(b.shape)
plt.plot(b[:, 10])